(function(){
  'use strict';
  const correct={space:'illegal',resident:'zhiheng',cause:'known-system',records:'cleanup',current:'risk'};
  const support={space:['downloads','archive'],resident:['tickets','photo','archive'],cause:['tickets','notice2023','exhaust'],records:['legal','archive','photo2021'],current:['notice2026','room1403','exhaust']};
  function availableSources(){const s=QishanState?QishanState.get():{visitedPages:[]};return (s.visitedPages||[]).map(x=>x.path)}
  function setupSources(){const paths=availableSources();document.querySelectorAll('.support-grid').forEach(g=>{let shown=0;g.querySelectorAll('label[data-source]').forEach(l=>{const key=l.dataset.source;const ok=paths.some(p=>p.includes(key));l.classList.toggle('unavailable',!ok);l.querySelector('input').disabled=!ok;if(ok)shown++});if(!shown){const p=document.createElement('div');p.className='support-empty';p.textContent='最近浏览记录中暂时没有可附到这一项的页面。';g.appendChild(p)}})}
  function evaluate(fd){const claims={},evidence={};Object.keys(correct).forEach(k=>{claims[k]={selected:fd.get(k),correct:fd.get(k)===correct[k]};const vals=fd.getAll('support_'+k);evidence[k]={selected:vals,valid:vals.filter(v=>support[k].includes(v))}});return {claims,evidence}}
  function complete(e){return Object.keys(correct).every(k=>e.claims[k].correct&&e.evidence[k].valid.length>=1)}
  document.addEventListener('DOMContentLoaded',()=>{setupSources();const form=document.querySelector('#risk-form');if(!form)return;form.addEventListener('submit',ev=>{ev.preventDefault();const fd=new FormData(form),data=evaluate(fd),action=fd.get('action');const s=QishanState?QishanState.get():{visitedPages:[]};const paths=(s.visitedPages||[]).map(x=>x.path);const foundLan=paths.some(p=>p.includes('/news/2024-archive-thanks.html'));let ending='avoid';const corePublic=data.claims.cause.correct&&data.claims.records.correct&&data.evidence.cause.valid.length&&data.evidence.records.valid.length;const correctCount=Object.values(data.claims).filter(x=>x.correct).length;const evidenceCount=Object.values(data.evidence).filter(x=>x.valid.length).length;if(action==='public'&&corePublic&&correctCount>=4&&evidenceCount>=3)ending='public';if(action==='family'&&complete(data)&&foundLan)ending='archive';QishanState&&QishanState.patch({finalClaims:{...data,action,submittedAt:Date.now()},ending});location.href='result.html'})})
})();
