(function(){
  'use strict';
  const synonym={repair:'维修',ticket:'工单',parking:'停车',visitor:'访客',exhaust:'排风',ventilation:'排风',umbrella:'雨伞',archive:'归档',renovation:'旧改',zhiheng:'周芷珩',air:'排风',duct:'风道',vent:'排风',lost:'失物',notice:'公告',repairing:'维修'};
  function clean(s){return String(s||'').toLowerCase().replace(/[，。；、/\\\s_-]+/g,'').replace(/a栋/g,'a').replace(/14-04/g,'1404')}
  function terms(q){const raw=String(q||'').trim().toLowerCase().split(/[\s,，、/]+/).filter(Boolean);return raw.map(x=>synonym[x]||x).map(clean).filter(Boolean)}
  function score(item,q){const ts=terms(q);if(!ts.length)return 0;const title=clean(item.title),snip=clean(item.snippet),cat=clean(item.category),date=clean(item.date);const words=(item.keywords||[]).concat(item.aliases||[]).map(clean);let total=0,matched=0;for(const t of ts){let best=0;if(title.includes(t))best=Math.max(best,10);if(words.some(w=>w===t))best=Math.max(best,9);if(words.some(w=>w.includes(t)||t.includes(w)))best=Math.max(best,6);if(snip.includes(t))best=Math.max(best,4);if(cat.includes(t)||date.includes(t))best=Math.max(best,2);if(best){matched++;total+=best}}return matched===ts.length?total+matched:0}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function reEsc(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
  function highlight(text,q){let html=esc(text),raw=String(q||'').trim().split(/[\s,，、/]+/).filter(Boolean).map(x=>synonym[x.toLowerCase()]||x).filter(x=>String(x).length>1);for(const t0 of raw){try{html=html.replace(new RegExp('('+reEsc(esc(t0))+')','ig'),'<mark>$1</mark>')}catch(e){}}return html}
  function render(){const box=document.querySelector('#search-results');if(!box||!window.SEARCH_INDEX)return;const p=new URLSearchParams(location.search),q=(p.get('q')||'').trim(),input=document.querySelector('#main-search-input');if(input)input.value=q;const count=document.querySelector('#result-count');if(!q){if(count)count.textContent='';return}QishanState&&QishanState.search(q);const rows=SEARCH_INDEX.map(x=>({s:score(x,q),x})).filter(r=>r.s>0).sort((a,b)=>b.s-a.s||b.x.date.localeCompare(a.x.date)).map(r=>r.x);if(count)count.textContent=`${rows.length} 条结果`;const root=document.body.dataset.root||'';if(!rows.length){box.innerHTML='<div class="empty-state">没有找到匹配的公开内容。可尝试房号、姓名、日期、工单号或服务词的其他写法。</div>';return}box.innerHTML=rows.map(r=>`<article class="search-result"><div class="meta">${esc(r.category)} · ${esc(r.date)}</div><h2><a href="${root+r.url}">${highlight(r.title,q)}</a></h2><div class="snippet">${highlight(r.snippet,q)}</div></article>`).join('')}
  document.addEventListener('DOMContentLoaded',render);
})();
